### ISSUE TITLE
Available component "+" and "-" button issue.

### ISSUE THREAD

**Issue by henrywang** [weldr/cockpit-composer#216]
### Description of problem
The available component add or remove button should be constant after clicking Discard Changes

### Component (web, API, etc)
web

### Version or commit hash (if applicable)
ac8be5731024b3fcf54f1da73565dedd505253a0

### How often reproducible
100%

### Steps to Reproduce

1. go to edit blueprint page.
2. make a component change.
3. click discard changes button.

### Actual results
The "+" should be "+" and "-" should be "-".
### Expected results
All "-" button changed to "+".

**Comment by atodorov** [comment]
From what I can tell "Discard changes" doesn't really discard anything. Maybe that's the problem.

**Comment by jgiardino** [comment]
I'm not able to reproduce this issue.

**Comment by KKoukiou** [comment]
Indeed I confirm that this issue is not reproducable. @henrywang please verify as well and close the issue if not more applicable.
