### ISSUE TITLE
Loading forever when entering edit blueprint page directly.

### ISSUE THREAD

**Issue by henrywang** [weldr/cockpit-composer#286]
### Description of problem
Go to edit blueprint page directly by enter URL: http://localhost:9090/welder#/edit/test. The Available Components and Blueprint Components keep on loading and content cannot be loaded.
![screenshot_2018-07-10 image builder - cockpit](https://user-images.githubusercontent.com/672230/42489535-2d34a538-843e-11e8-900c-f7eae21bbe4b.png)
### Component (web, API, etc)
web

### Steps to Reproduce

1. Go to edit blueprint page directly by enter URL: http://localhost:9090/welder#/edit/test
2. Wait for content loaded

### Actual results
Loading ...

### Expected results
Load available components and selected components

### Additional info
No this kind of issue when entering edit blueprint page by clicking Edit Blueprint button from blueprints page.

**Comment by jgiardino** [comment]
@henrywang Can you confirm that this issue occurs when the build is connected to the composer api?

**Comment by henrywang** [comment]
@jgiardino, yes. If I go back to blueprints page and enter edit blueprint page by clicking edit blueprint button, it works.

**Comment by jgiardino** [comment]
Per discussion with @henrywang, @jkozol and @larskarlitski, we think the flaky testing might be related to this issue.

**Comment by KKoukiou** [comment]
I can navigate to the blueprint edit URL directly without any issue. It just takes some time to load because it is fetching the blueprints and everything, as if you loaded the initial page directly. But it definitely gives a list for components after some seconds for me.
