### ISSUE TITLE
Error handling for blueprint names

### ISSUE THREAD

**Issue by jgiardino** [weldr/cockpit-composer#317]
When creating a new blueprint, an api call will return an error if any characters that are not allowed are used. If that occurs:

- The modal remains open
- An error message should display to the user in the Create Blueprint modal explaining what the issue is with the name.

NOTE: this issue requires updates to the api

**Comment by larskarlitski** [comment]
> NOTE: this issue requires updates to the api

The API seems to handle this correctly now:

```
# cat foo.toml 
name = "foo bar"
description = ""
version = "0.0.5"
modules = []
groups = []

# composer-cli blueprints push foo.toml 
2018-09-12 10:44:41,908: Invalid characters in API path
```

**Comment by atodorov** [comment]
Note: this can be easily tested with the existing test suite, we already have a case which creates a new blueprint, just need to pass a name with spaces and make sure the UI gives an error instead.

**Comment by henrywang** [comment]
@jgiardino and @larskarlitski, I think we need to mark this issue with a higher priority because it looks weird in the UI. There's no alert in the UI and blueprint is able to be created but cannot be edited from UI.
It's very common to have two or more words as blueprint name.
