### ISSUE TITLE
UI with lorax-composer: add 389-ds-base: no progress, can't save

### ISSUE THREAD

**Issue by atodorov** [weldr/cockpit-composer#338]
### Version or commit hash (if applicable)
cockpit-composer-0.1.1-1.el7.noarch

### How often reproducible
always

### Steps to Reproduce

1. Create new blueprint
2. Proceed to adding new components
3. Click the + button

### Actual results
+ button turns into -, component icon is updated to indicate it has been added to the blueprint. However the component and its dependencies doesn't appear on the right hand side of the UI.

Moreover I also don't see any progress indication that something else is going on, e.g. a depsolve.

**Comment by jgiardino** [comment]
I believe this issue is fixed with #830, and so I'm closing this issue.
