### ISSUE TITLE
No good error state if the lorax-composer.service is not running

### ISSUE THREAD

**Issue by andreasn** [weldr/cockpit-composer#460]
If lorax-composer.service isn't running, I get this:
![screenshot from 2018-11-27 11-38-31](https://user-images.githubusercontent.com/209895/49076421-420ce880-f239-11e8-9809-6150f4055a7d.png)

The error state is very vague, and offers little guidance on how to get out of this state.

Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1708387

**Comment by andreasn** [comment]
Design, following what we did in https://github.com/cockpit-project/cockpit/pull/8493

![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/composer/empty-state.png)

**Comment by andreasn** [comment]
@jgiardino @garrett looks good?

**Comment by jgiardino** [comment]
Thanks for mocking this up! Overall I like this! Comments/questions below...

- I'm not sure if we have what we need to implement this in the UI yet. 
- What were you thinking would happen if the user clicks Troubleshoot?
- Is the checkbox deselected by default? Is it intended to automatically start the service and never show this error state again?

**Comment by andreasn** [comment]
> I'm not sure if we have what we need to implement this in the UI yet.

There are various other places in Cockpit where we do something similar, so I think it's fairly straight forward to implement.

> What were you thinking would happen if the user clicks Troubleshoot?

Takes you to the Services page for lorax-composer. Allows you to see the logs of the service, start it, enable (so it launches on boot) it, or both.

> Is the checkbox deselected by default? Is it intended to automatically start the service and never show this error state again?

Yes, if you leave the box checked and hit "Start Service", this will never show again.
@martinpitt in the libvirt case the checkbox is checked by default, right?

**Comment by martinpitt** [comment]
@andreasn: Yes, also on the Machines page.

**Comment by garrett** [comment]
LGTM! :+1:

**Comment by larskarlitski** [comment]
This came up again as https://github.com/weldr/welder-web/issues/638 and I've helped a lot of people over the last months who were confused by it. Does someone have time to have a look?

**Comment by jgiardino** [comment]
I will take a look today.

**Comment by martinpitt** [comment]
Can be modelled after https://github.com/cockpit-project/cockpit-podman/commit/24665af7d0f7d2529b34f0797eeba380ec60e4a0
