### ISSUE TITLE
The selected component should have "-" button in it, not "+" button

### ISSUE THREAD

**Issue by henrywang** [weldr/cockpit-composer#471]
When component/components were added into blueprint, that component should have a "-" button, not "+" button, and the button should be bordered.
This issue is easy to reproduced in end to end test.
![should_have_minus_button](https://user-images.githubusercontent.com/672230/49978121-ffab1180-ff83-11e8-8096-18bdf476001e.png)

**Comment by jgiardino** [comment]
@henrywang Are you still able to reproduce this issue?

**Comment by KKoukiou** [comment]
I think we can close this, I can' reproduce this either.

If someone hits this behavior again we can re-open the issue.
