### ISSUE TITLE
`make upload-pot` fails: read-only?

### ISSUE THREAD

**Issue by martinpitt** [weldr/cockpit-composer#672]
### Description of problem

When our bots do a translation update, it [silently fails](https://209.132.184.41:8493/logs/po-refresh-645-20190425-045151/log):
```
> [react-intl-po] write file -> po/welder-web.pot ✔️

Error: Project or Version might be in Read-Only mode: [project: welder-web, version: master]
```

I reproduced that  interactively on a current run, too. Maybe we are missing some credentials in the pods, or does this generally not work?

**Comment by martinpitt** [comment]
"Silently" because it exits with code 0, so we don't notice if it fails.

**Comment by larskarlitski** [comment]
Unfortunately, `zanata-js` doesn't exit with non-zero on error. Shall we switch to the official zanata tool?

**Comment by martinpitt** [comment]
I fixed the permissions of cockpit in the zanata project, works now.
