### ISSUE TITLE
please migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [weldr/cockpit-composer#856]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:
* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:
* For github hosted projects, Weblate open pull request. For other project, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by marusak** [comment]
Hey,
so this is very similar to what we did in cockpit-podman.
We want `cockpit-composer` project with `master` component. This component points to [cockpit-composer-weblate](https://github.com/weldr/cockpit-composer-weblate) repository to master branch.
I already pushed there current `.pot` file and all `.po` files. Also added `weblate` user as contributor. We want direct commits, no PRs.

> * [mandatory] which branch is your development branch?

master

> * [mandatory] have you merged latest translation from Zanata and locked the project?

Yes.

> * [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)

MIT

> * [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)

No.

> * [optional] do you need us to activate any specific checks? (this is a setting per component [3])

The usual set + python brace format (it is JS, but strings look like "The user {userName} is not permitted to start services.".

> * [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

No.

Thank you!

**Comment by Jibec** [comment]
Done: 
https://translate.stg.fedoraproject.org/projects/cockpit-composer/cockpit-composer/

Martin and you are admin

**Comment by marusak** [comment]
Thanks :)
Could the component please be `master` and not `cockpit-composer`?

**Comment by marusak** [comment]
Also url was using https, not ssh, so I changed that too - so we get direct commits and not PRs (as we already got)

**Comment by marusak** [comment]
Ech, and one more problem. I squashed the commit it sent and now there is merge conflict. How can I deal with it?

**Comment by Jibec** [comment]
done, all changes were applied
